function init(){
    loadHeader();
}

function loadHeader(){

    document.getElementById("email-header").innerHTML = 
        "<h1 id=\"logo\"><a href = \"inbox.html\">EMAIL</a></h1>"
        + "<div class=\"search-container\">"
        + "<form action=\"bug.html\">"
        + "<input type=\"text\" placeholder=\"Search..\" name=\"search\">"
        + "<button type=\"submit\">Search</button>"
        + "</form></div>";
}

function gotIt(){
    var banner = document.getElementById("banner-notif");
    banner.style.display = "none";
}

//takes int x and opens corresponding email
function openEmail(list, x){
    //add error checking
    var modal = document.getElementById("myModal");
    
    var emailAddress = document.getElementById("email");
    var sender = document.getElementById("sender");
    var subject = document.getElementById("subject");
    var email = document.getElementById("body");

    emailAddress.innerHTML = list[x].senderEmail;
    sender.innerHTML = list[x].sender;
    subject.innerHTML = "Subject: " + list[x].subject;
    email.innerHTML = list[x].text; 
    //display modal
    modal.style.display = "block";
   
}

//generates the email of emailNum at certain rowNum in the table
function generateEmailPrev(list, emailNum){
    var table = document.getElementById("email-table");

    var row = table.insertRow(emailNum);
    row.className = "email-prev";
    row.onclick= function() {openEmail(list, emailNum)};

    var sender = row.insertCell(0);
    sender.className="from";
    var subject = row.insertCell(1);
    subject.className = "preview";
    var time = row.insertCell(2);
    time.className = "time";

    var emailObj = list[emailNum];
    sender.innerHTML = emailObj.sender;
    subject.innerHTML = emailObj.subject;
    time.innerHTML = emailObj.time;
}

function loadEmailPrevs(list){
    for(var i = 0; i < list.length; i++){
        generateEmailPrev(list, i);
    }
}

function closeEmail(){
    var modal = document.getElementById("myModal");
    modal.style.display = "none";
}

//Email structure: senderEmail, sender, subject, time, text
var inboxEmails = [];

inboxEmails.push({
    senderEmail: "auto-noreply@email.com",
    sender: "System Notification",
    subject: "[IMPORTANT] Notification of Inbox Termination",
    time: "8:43AM",
    text: `Gregor Samsa, <br> <br>
    This is an autogenerated notification email to let you know that 
    this inbox {gregor.samsa@amazoff.com} will be archived in 24 hours. It will no longer receive incoming
    emails or be able to send outgoing mail. It will be archived at the
    request of {Jefe Bezos} for the following reason:

    <br><br> Temination of Employment
    <br><br> Please take appropriate measures and proceed accordingly.
    If you think this was a mistake please contact {Jefe.Bezos@amazoff.com}.
    `
});

inboxEmails.push({
    senderEmail: "greteSa@email.com",
    sender: "Grete Samsa",
    subject: "Deepest Regrets",
    time: "8:43AM",
    text: `Gregor, <br> <br>
    I hope this email finds you well. I've slept very poorly the past few days, 
    knowing what we've done to you. I don't know if you still 
    check your inbox, or if you even still have your computer.
    I just want you to know how sorry I am.

    <br><br> Love, <br> Grete`
});



inboxEmails.push({
    senderEmail: "rosa.line@stonybrook.edu",
    sender: "Rosa Line",
    subject: "Concerning the news",
    time: "02/04/12",
    text: `Hi Gregor, <br> <br>
    I heard about your affliction through a mutual acquaintance. 
    I am very sorry to hear that you can no longer get up on your own 
    in the mornings. From what I hear, you have transformed quite a bit. 
    <br> I think I know someone who may be able to help. Let me know if you
    want to discuss this over coffee.
    <br><br> Best, <br> Rosa`
});

inboxEmails.push({
    senderEmail: "Sal.Lami@stonybrook.edu",
    sender: "Sal Lami",
    subject: "About out Collaboration",
    time: "8:43",
    text: `Hi Gregor, <br> <br>
    My condolences for your unfortunate condition. I can't 
    imagine what it's like to be in your position right now. 
    I am inexperienced in such matters, but perhaps an entomologist 
    would be able to shed some light into what is happening. 
    Once again, best of luck regarding your health. 
    <br><br>If you need to take time off from our collaboration 
    to recooperate, I completely understand.

    <br><br> Sincerely, <br> Sam`
});

inboxEmails.push({
    senderEmail: "employee-notification@amazoff.com",
    sender: "Amazoff Announcements",
    subject: "Announcement",
    time: "02/04/19",
    text: `Hello Amazoff Family, <br> <br>
    Following the incident report from one of our employees, we have 
    temporarily stopped the use of pesticides in our building. 
    If you notice any extra bugs (pun intended), please do not be alarmed. 
    <br> And as always, if you are in the technology dept, 
    please flag bugs in your code properly. I'm looking at you SEAN!
    <br><br>Best, <br> Amazoff
    `
});

inboxEmails.push({
    senderEmail: "Devon.Russo@amazoff.com",
    sender: "Devon Russo",
    subject: "Hey man",
    time: "8:43AM",
    text: ` Hey man, <br><br>
    It's your marketing colleague, Devon. I know we've never talked even though
    we work in the same department, but
    I heard what happened to you, and I was checking in to see if you were
    alright. If you ever need anything, just let me know. 

    <br><br> Best, <br> your man Devon`
});

inboxEmails.push({
    senderEmail: "greteSa@email.com",
    sender: "Grete Samsa",
    subject: "Lunch",
    time: "02/04/19",
    text: `Hey Gregor, <br> <br>
    I know you can't use your phone anymore, but I wanted to know that you
    forgot your lunch at home this morning. As your responsible younger sister,
    there's no way I could let you go hungry. I had your lunch sent to the office.
    I hope you don't mind me sending this to your work email. 

    <br><br>Love, <br> Grete 
    `
});

inboxEmails.push({
    senderEmail: "Jefe.Bezos@amazoff.com",
    sender: "Jefe Bezos",
    subject: "Emergency Meeting Tomorrow",
    time: "02/04/19",
    text: `Hello, <br> <br>
    We will be having a meeting in conference room B to discuss your special
    circumstances. Please let me know if you can make it.
    <br><br>Best, <br> Jefe Bezos <br> CEO of Amazoff
    `
});

inboxEmails.push({
    senderEmail: "SamStanley@vector.com",
    sender: "Samuel Stanley",
    subject: "Reaching out about marketing",
    time: "02/04/19",
    text: `Hello Gregor, <br> <br>
    I hope this email finds you well. My name is Samuel Stanley, and I 
    am reaching out to you about selling our knives. I was introduced 
    to you by a friend, Steve Vector. Our knives are of good quality, 
    and my company would be willing to give a discount for bulk purchases. 
    Please let me know what you think of this offer. 
    <br><br>Best, <br> Samuel <br> 
    `
});

//Email structure: senderEmail, sender, subject, time, text
var starredEmails = [];


//Email structure: senderEmail, sender, subject, time, text
var draftEmails = [];

//Email structure: senderEmail, sender, subject, time, text
var sentEmails = [];

sentEmails.push({
    senderEmail: "gregor.samsa@amazoff.com",
    sender: "Gregor Samsa",
    subject: "RE: Emergency Meeting Tomorrow",
    time: "02/04/19",
    text: `Mr. Bezos <br> <br>
    I wi;l; b tgere.

    <br><br> Sonsertely, <br> Grefpr`
});

//Email structure: senderEmail, sender, subject, time, text
var spamEmail = [];

spamEmail[0] = {
    senderEmail: "",
    sender: "",
    subject: "",
    time: "",
    text: ``
};